theme: jekyll-theme-cayman
# Site settings
title: Vison, Signal, AI++    				  	#你博客的标题
SEOTitle: 哲宇的博客 | Zheyu Wen's blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: image/profile.jpg  	#显示在首页的背景图片
email: zheyw@umich.edu	
description: "signal, image processing and machine learning"  			 #网站介绍
keyword: "DSP, Deep Learning" #关键词
url: "https://CoderNoMercy.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
